name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        version: [12, 13, 14, 15]
      fail-fast: false

    name: Build (macos-${{ matrix.version }})

    runs-on: macos-${{ matrix.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: make enable

